/**
 * WayAbroad — Admission Probability Engine (v2)
 * -----------------------------------------------------------------------------
 * The "killer feature": given a student profile + a program, return an EXPLAINABLE
 * admission estimate with a confidence band, a reach/match/safety read, and the drivers
 * behind it. Pure, dependency-free, unit-tested.
 *
 * v2 change (per docs/superpowers/specs/2026-05-31-ai-data-validation-and-calculator-design.md):
 * the old "empirical blend" read back synthetic admission_records that were generated by the
 * very same formula as the prior — circular, fake signal. That is GONE. The base rate now comes
 * from a real, cited acceptance rate when one exists (from the AI web-search validator), and
 * falls back to a clearly-labeled rough tier prior otherwise. The student's GPA and language
 * strength adjust the estimate around that base; hard requirements still gate it.
 *
 * NEVER render a bare percentage — always show the band + drivers + the reach/match/safety read.
 */

export type LangTest = "IELTS" | "TOEFL" | "TOPIK";
export type TierBand = "elite" | "strong" | "mid" | "regional";

export interface StudentProfile {
  gpa: number; // normalized to a 4.0 scale
  langTest: LangTest | null;
  langScore: number | null; // IELTS 0-9, TOEFL iBT 0-120, or TOPIK level 1-6
}

export interface ProgramInfo {
  name?: string;
  language: "English" | "Korean";
  minGpa: number; // on 4.0 scale
  minIelts?: number | null;
  minToefl?: number | null;
  minTopik?: number | null;
  tierBand?: TierBand;
}

/** A validated, cited acceptance rate for the program/university (from the data validator). */
export interface AcceptanceBaseRate {
  rate: number; // 0..1
  sourceUrl?: string | null;
  international?: boolean;
}

export type Category = "reach" | "match" | "safety";

export interface Driver {
  factor: string;
  impact: "positive" | "negative" | "neutral";
  detail: string;
}

export interface ProbabilityResult {
  percent: number; // 0-100, the headline number
  band: [number, number]; // confidence interval in percent
  confidence: "low" | "moderate"; // never "high" — we have no per-applicant outcome data
  category: Category; // reach / match / safety
  basis: "validated_rate" | "prior"; // where the base rate came from
  eligible: boolean; // language confirmed+met AND GPA within 0.3 of the minimum
  languageConfirmed: boolean; // false when no usable test is on file
  drivers: Driver[];
  disclaimer: string;
}

// Rough prior admit-rate by selectivity tier — used ONLY when no real acceptance rate is known,
// and always labeled as a rough estimate in the UI.
const TIER_BASE: Record<TierBand, number> = {
  elite: 0.3,
  strong: 0.5,
  mid: 0.68,
  regional: 0.82,
};

const clamp = (x: number, lo: number, hi: number) =>
  Math.max(lo, Math.min(hi, x));

interface LangFit {
  met: boolean;
  margin: number;
  note: string;
  unknown: boolean;
}

function languageFit(student: StudentProfile, program: ProgramInfo): LangFit {
  if (student.langTest == null || student.langScore == null) {
    return { met: false, margin: 0, note: "no test on file", unknown: true };
  }
  const score = student.langScore;
  if (program.language === "Korean") {
    const min = program.minTopik ?? 3;
    const lvl = student.langTest === "TOPIK" ? score : 0;
    return {
      met: lvl >= min,
      margin: lvl - min,
      note: `TOPIK ${lvl || "—"} vs required ${min}`,
      unknown: false,
    };
  }
  if (student.langTest === "IELTS") {
    const min = program.minIelts ?? 6.0;
    return {
      met: score >= min,
      margin: score - min,
      note: `IELTS ${score} vs required ${min}`,
      unknown: false,
    };
  }
  if (student.langTest === "TOEFL") {
    const min = program.minToefl ?? 80;
    return {
      met: score >= min,
      margin: (score - min) / 10,
      note: `TOEFL ${score} vs required ${min}`,
      unknown: false,
    };
  }
  // Student has TOPIK but the program is English-taught — can't confirm an English requirement.
  return {
    met: false,
    margin: 0,
    note: `TOPIK ${score} on file, but this program needs English proof (IELTS/TOEFL)`,
    unknown: true,
  };
}

/**
 * Core scoring function. Pure and deterministic.
 * @param baseRate optional validated, cited acceptance rate; when absent a labeled tier prior is used.
 */
export function scoreAdmission(
  student: StudentProfile,
  program: ProgramInfo,
  baseRate?: AcceptanceBaseRate | null,
): ProbabilityResult {
  const drivers: Driver[] = [];
  const tier = program.tierBand ?? "mid";
  const lang = languageFit(student, program);

  // --- 1. Language eligibility ---
  if (lang.unknown) {
    drivers.push({
      factor: "Language proficiency",
      impact: "neutral",
      detail:
        "No language test on file yet — add one to confirm eligibility and sharpen this estimate.",
    });
  } else if (lang.met) {
    drivers.push({
      factor: "Language proficiency",
      impact:
        lang.margin >= (program.language === "Korean" ? 1 : 0.5)
          ? "positive"
          : "neutral",
      detail: `Meets requirement (${lang.note}).`,
    });
  } else {
    drivers.push({
      factor: "Language proficiency",
      impact: "negative",
      detail: `Below requirement (${lang.note}). This is usually a hard gate — improving it most increases your odds.`,
    });
  }

  // --- 2. GPA fit ---
  const gpaMargin = student.gpa - program.minGpa;
  drivers.push({
    factor: "Academic record (GPA)",
    impact:
      gpaMargin >= 0.2 ? "positive" : gpaMargin < 0 ? "negative" : "neutral",
    detail: `Your GPA ${student.gpa.toFixed(2)} vs program minimum ${program.minGpa.toFixed(2)} (margin ${gpaMargin >= 0 ? "+" : ""}${gpaMargin.toFixed(2)}).`,
  });

  // --- 3. Base rate: real cited acceptance rate, else a labeled rough tier prior ---
  const hasValidatedRate =
    baseRate != null && Number.isFinite(baseRate.rate) && baseRate.rate > 0;
  const base = hasValidatedRate
    ? clamp(baseRate!.rate, 0.02, 0.98)
    : TIER_BASE[tier];
  if (hasValidatedRate) {
    drivers.push({
      factor: "Program selectivity",
      impact: base <= 0.25 ? "negative" : base >= 0.6 ? "positive" : "neutral",
      detail: `Based on ${baseRate!.international ? "the international " : "an "}acceptance rate of ~${Math.round(base * 100)}%${baseRate!.sourceUrl ? " (validated from a cited source)" : ""}.`,
    });
  } else {
    drivers.push({
      factor: "Program selectivity",
      impact:
        tier === "elite"
          ? "negative"
          : tier === "regional"
            ? "positive"
            : "neutral",
      detail: `${tier[0]!.toUpperCase() + tier.slice(1)}-tier program — rough baseline ~${Math.round(base * 100)}% (no published acceptance rate found; estimate only).`,
    });
  }

  // --- 4. Fit: move around the base rate by GPA margin + language strength ---
  let fit = clamp(gpaMargin * 0.3, -0.35, 0.35);
  if (lang.met) {
    fit += clamp(
      lang.margin * (program.language === "Korean" ? 0.04 : 0.05),
      0,
      0.1,
    );
  }
  let posterior = clamp(base + fit, 0.03, 0.97);

  // --- 4b. Hard gates (dominate, so the headline matches the eligibility/category) ---
  if (!lang.unknown && !lang.met) posterior *= 0.25;
  // GPA well below the minimum is a hard gate: cap low so a high base rate can't leave the
  // headline looking like a match/safety while the verdict is reach/ineligible.
  if (gpaMargin < -0.3) posterior = Math.min(posterior * 0.5, 0.18);
  posterior = clamp(posterior, 0.03, 0.97);

  // --- 5. Band + confidence reflect the BASIS, not fake sample size ---
  const eligible = !lang.unknown && lang.met && gpaMargin >= -0.3;
  let half = hasValidatedRate ? 8 : 12;
  if (lang.unknown) half += 6;
  const confidence: ProbabilityResult["confidence"] =
    hasValidatedRate && !lang.unknown ? "moderate" : "low";

  const percent = Math.round(posterior * 100);
  const band: [number, number] = [
    clamp(percent - half, 1, 99),
    clamp(percent + half, 1, 99),
  ];

  const category: Category = !eligible
    ? "reach"
    : percent >= 55
      ? "safety"
      : percent >= 30
        ? "match"
        : "reach";

  return {
    percent,
    band,
    confidence,
    category,
    basis: hasValidatedRate ? "validated_rate" : "prior",
    eligible,
    languageConfirmed: !lang.unknown,
    drivers,
    disclaimer:
      "A model estimate from the program's selectivity and your academic/language fit" +
      (hasValidatedRate
        ? ", anchored to a cited acceptance rate"
        : " (no published acceptance rate was found, so the baseline is a rough tier estimate)") +
      ". Not a prediction or an official decision — confirm requirements with the university.",
  };
}
